require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

# react-native-firebase + use_frameworks:static + RN prebuilt: build RNFB as static libraries
# so React headers/RCT_* macros resolve (see invertase/react-native-firebase#8883, #8930).
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.start_with?('RNFB')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end

prepare_react_native_project!

target 'boltexponativewind' do
  $RNFirebaseAsStaticFramework = true

  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  # Firebase Swift/static library compatibility (required for FirebaseAuth-Swift.h to be found)
  use_frameworks! :linkage => :static
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true
  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    pods_root = installer.sandbox.root.to_s

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    # Fix PhaseScriptExecution failures: CocoaPods scripts use realpath -mq in error handler,
    # which can fail on some macOS versions. Use portable path in trap.
    Dir[File.join(pods_root, 'Target Support Files/**/*.sh')].each do |script_path|
      content = File.read(script_path)
      if content.include?('realpath -mq')
        File.write(script_path, content.gsub('$(realpath -mq "${0}")', '"${0}"'))
      end
    end

    # React Native Firebase: allow non-modular React-Core headers inside RNFB framework modules
    installer.pods_project.targets.each do |target|
      if target.name.start_with?('RNFB')
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
      end
    end

    # Xcode 26 / prebuilt RN: symlink HostPlatform* headers from React-Core-prebuilt
    # into React-Fabric public headers so codegen and safe-area-context can find them
    fabric_view = File.join(pods_root, 'Headers/Public/React-Fabric/react/renderer/components/view')
    prebuilt_fabric = File.join(pods_root, 'React-Core-prebuilt/React.xcframework/ios-arm64/React.framework/Headers/React_Fabric')
    %w[HostPlatformViewProps.h HostPlatformViewEventEmitter.h HostPlatformTouch.h HostPlatformViewTraitsInitializer.h].each do |name|
      src = File.join(prebuilt_fabric, name)
      dst = File.join(fabric_view, name)
      FileUtils.ln_sf(src, dst) if File.exist?(src) && !File.exist?(dst)
    end
    # graphics (ReactCodegen, conversions, etc. need all React_graphics headers)
    fabric_graphics = File.join(pods_root, 'Headers/Public/React-Fabric/react/renderer/graphics')
    prebuilt_graphics = File.join(pods_root, 'React-Core-prebuilt/React.xcframework/ios-arm64/React.framework/Headers/React_graphics')
    FileUtils.mkdir_p(fabric_graphics)
    if Dir.exist?(prebuilt_graphics)
      Dir.children(prebuilt_graphics).each do |name|
        next unless name.end_with?('.h')
        src = File.join(prebuilt_graphics, name)
        dst = File.join(fabric_graphics, name)
        FileUtils.ln_sf(src, dst) if File.file?(src)
      end
    end
    # imagemanager (react-native-screens and others need RCTImagePrimitivesConversions.h)
    fabric_imagemanager = File.join(pods_root, 'Headers/Public/React-Fabric/react/renderer/imagemanager')
    prebuilt_imagemanager = File.join(pods_root, 'React-Core-prebuilt/React.xcframework/ios-arm64/React.framework/Headers/React_ImageManager')
    FileUtils.mkdir_p(fabric_imagemanager)
    if Dir.exist?(prebuilt_imagemanager)
      Dir.children(prebuilt_imagemanager).each do |name|
        next unless name.end_with?('.h')
        src = File.join(prebuilt_imagemanager, name)
        dst = File.join(fabric_imagemanager, name)
        FileUtils.ln_sf(src, dst) if File.file?(src)
      end
    end
    # React-FabricComponents: prebuilt has flat headers; map to component subdirs for include path
    prebuilt_fabric_comps = File.join(pods_root, 'React-Core-prebuilt/React.xcframework/ios-arm64/React.framework/Headers/React_FabricComponents')
    fabric_comps_base = File.join(pods_root, 'Headers/Public/React-FabricComponents/react/renderer/components')
    if Dir.exist?(prebuilt_fabric_comps)
      comp_map = {
        'text' => %w[Paragraph BaseText RawText Text RCTAttributed RCTFont RCTText EventEmitters Props ShadowNodes States ComponentDescriptors],
        'scrollview' => %w[ScrollView BaseScrollView HostPlatformScrollView],
        'modal' => %w[ModalHostView],
        'safeareaview' => %w[SafeAreaView],
        'inputaccessory' => %w[InputAccessory],
        'textinput' => %w[AndroidTextInput BaseTextInput],
        'switch' => %w[AppleSwitch]
      }
      Dir.children(prebuilt_fabric_comps).each do |name|
        next unless name.end_with?('.h')
        src = File.join(prebuilt_fabric_comps, name)
        next unless File.file?(src)
        dir = comp_map.find { |_, prefixes| prefixes.any? { |p| name.start_with?(p) } }
        subdir = dir ? dir[0] : 'text'
        dst_dir = File.join(fabric_comps_base, subdir)
        FileUtils.mkdir_p(dst_dir)
        FileUtils.ln_sf(src, File.join(dst_dir, name))
      end
    end
    # textlayoutmanager (ParagraphState.h includes TextLayoutManager.h)
    fabric_textlayout = File.join(pods_root, 'Headers/Public/React-FabricComponents/react/renderer/textlayoutmanager')
    FileUtils.mkdir_p(fabric_textlayout)
    %w[TextLayoutManager.h TextLayoutManagerExtended.h].each do |name|
      src = File.join(prebuilt_fabric_comps, name)
      FileUtils.ln_sf(src, File.join(fabric_textlayout, name)) if File.exist?(src)
    end
  end
end
