import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/colors';

/** Match Home / TemplatePreview app header bar. */
const APP_HEADER_PRIMARY = '#8B1A3D';
const APP_HEADER_ACCENT = '#EAB308';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    backgroundColor: APP_HEADER_PRIMARY,
    paddingTop: 36,
    paddingBottom: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 6,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerButtonDisabled: {
    opacity: 0.3,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: APP_HEADER_ACCENT,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 4,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: APP_HEADER_PRIMARY,
    fontSize: 14,
    fontWeight: '600',
  },
  canvasContainer: {
    flex: 1,
  },
  canvasContent: {
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 0, // Remove horizontal padding to eliminate side white space
  },
  canvasTouchable: {
    width: '100%',
    alignItems: 'center',
  },
  canvas: {
    backgroundColor: 'transparent', // Transparent to avoid white space showing
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
  },
  canvasImage: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
  },
  placeholderCanvas: {
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    color: '#9CA3AF',
    fontSize: 16,
  },
  textElement: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textElementText: {
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  textElementInput: {
    width: '100%',
    height: '100%',
    textAlign: 'center',
    backgroundColor: 'transparent',
    padding: 0,
    margin: 0,
  },
  textElementTouchable: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButton: {
    position: 'absolute',
    top: -12,
    left: -12,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  resizeHandle: {
    position: 'absolute',
    bottom: -12,
    right: -12,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fbbf24',
    borderWidth: 2,
    borderColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  addPhotoButton: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    overflow: 'hidden',
  },
  addPhotoText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 9,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  profilePhotoImage: {
    width: '100%',
    height: '100%',
    borderRadius: 46,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  addLogoButton: {
    position: 'absolute',
    bottom: 24,
    left: 24,
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  addLogoText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 8,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  addLogoButtonDisabled: {
    opacity: 0.5,
  },
  addLogoTextDisabled: {
    color: 'rgba(255, 255, 255, 0.5)',
  },
  propertiesPanel: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 10,
  },
  propertiesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  propertiesTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  propertiesTitleText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  doneButton: {
    fontSize: 12,
    fontWeight: '700',
    color: '#881337',
    backgroundColor: 'rgba(136, 19, 55, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  propertiesScroll: {
    paddingVertical: 8,
  },
  propertiesScrollContent: {
    paddingHorizontal: 16,
    gap: 16,
  },
  propertyButton: {
    alignItems: 'center',
    gap: 6,
    minWidth: 60,
  },
  propertyButtonActive: {},
  propertyIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  propertyIconActive: {
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: '#881337',
    shadowColor: '#881337',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  propertyLabel: {
    fontSize: 10,
    color: '#6B7280',
    fontWeight: '500',
  },
  propertyLabelActive: {
    color: '#881337',
    fontWeight: '600',
  },
  bottomActions: {
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  actionButton: {
    alignItems: 'center',
    gap: 6,
    minWidth: 64,
  },
  actionIcon: {
    width: 64,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionIconActive: {
    backgroundColor: 'rgba(136, 19, 55, 0.1)',
    borderWidth: 2,
    borderColor: 'rgba(136, 19, 55, 0.2)',
  },
  actionLabel: {
    fontSize: 11,
    color: '#6B7280',
    fontWeight: '500',
  },
  actionLabelActive: {
    color: '#881337',
    fontWeight: '600',
  },
  propertyOptionsPanel: {
    backgroundColor: '#F9FAFB',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  propertyOptionsScroll: {
    flexGrow: 0,
  },
  fontOption: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginRight: 12,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    minWidth: 100,
    alignItems: 'center',
  },
  fontOptionActive: {
    borderColor: '#881337',
    backgroundColor: 'rgba(136, 19, 55, 0.05)',
  },
  fontOptionText: {
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '500',
  },
  fontOptionTextActive: {
    color: '#881337',
    fontWeight: '700',
  },
  colorOption: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
    borderWidth: 3,
    borderColor: 'transparent',
  },
  colorOptionActive: {
    borderColor: '#881337',
    transform: [{ scale: 1.1 }],
  },
  sizeControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  sizeButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: '#881337',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sizeButtonText: {
    fontSize: 24,
    color: '#881337',
    fontWeight: '700',
  },
  sizeValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    minWidth: 60,
    textAlign: 'center',
  },
  sizeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
    marginBottom: 12,
    textAlign: 'center',
  },
  helpText: {
    fontSize: 11,
    color: '#9CA3AF',
    marginTop: 12,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  shadowOptions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  shadowOption: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    minWidth: 80,
    alignItems: 'center',
  },
  shadowOptionActive: {
    borderColor: '#881337',
    backgroundColor: 'rgba(136, 19, 55, 0.05)',
  },
  shadowOptionText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  formatOptions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  formatOption: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    gap: 8,
    minWidth: 90,
  },
  formatOptionActive: {
    borderColor: '#881337',
    backgroundColor: 'rgba(136, 19, 55, 0.05)',
  },
  formatIcon: {
    fontSize: 24,
    color: '#6B7280',
  },
  formatLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
  },
  logoContainer: {
    position: 'absolute',
    bottom: 24,
    left: 24,
    width: 64,
    height: 64,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 8,
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 10,
    borderWidth: 2,
    borderColor: 'rgba(136, 19, 55, 0.2)',
  },
  partyLogoImage: {
    width: '100%',
    height: '100%',
  },
  /** Vertical INDIPIX strip on the left; included in ViewShot / html2canvas exports */
  watermarkContainer: {
    position: 'absolute',
    right: 8,
    zIndex: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  watermarkImage: {
    width: '100%',
    height: '100%',
  },
});
